export const qtype_properties = {
Person :[
 { property_id: 1 , is_required: false }, 
 { property_id: 2 , is_required: false }, 
 { property_id: 3 , is_required: false }, 
 { property_id: 4 , is_required: false }, 
 { property_id: 5 , is_required: false }, 
 { property_id: 6 , is_required: false }, 
 { property_id: 7 , is_required: false }, 
 { property_id: 8 , is_required: false }, 
 { property_id: 9 , is_required: false }, 
 { property_id: 10 , is_required: false }, 
 { property_id: 11 , is_required: false }, 
 { property_id: 12 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 14 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 48 , is_required: false }, 
 { property_id: 50 , is_required: false }, 
],
CreativeWork :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
WebSite :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
Book :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
PublicationIssue :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
Article :[
 { property_id: 16 , is_required: true }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: true }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
SoftwareApplication :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
Game :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
Movie :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 22 , is_required: false }, 
 { property_id: 23 , is_required: false }, 
 { property_id: 24 , is_required: false }, 
 { property_id: 25 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
Painting :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
Photograph :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
MusicPlaylist :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 26 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
MusicAlbum :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 26 , is_required: false }, 
 { property_id: 27 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
MusicRecording :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 27 , is_required: false }, 
 { property_id: 28 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
CreativeWorkSeries :[
 { property_id: 15 , is_required: false }, 
 { property_id: 16 , is_required: false }, 
 { property_id: 17 , is_required: false }, 
 { property_id: 18 , is_required: false }, 
 { property_id: 19 , is_required: false }, 
 { property_id: 20 , is_required: false }, 
 { property_id: 21 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
Event :[
 { property_id: 16 , is_required: false }, 
 { property_id: 22 , is_required: false }, 
 { property_id: 29 , is_required: false }, 
 { property_id: 30 , is_required: false }, 
 { property_id: 31 , is_required: true }, 
 { property_id: 32 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
],
Organization :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
Corporation :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
EducationalOrganization :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
CollegeOrUniversity :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
ElementarySchool :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
HighSchool :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
MiddleSchool :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
Preschool :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
School :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
GovernmentOrganization :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
LocalBusiness :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
Store :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
MedicalOrganization :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
Hospital :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
NGO :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
PerformingGroup :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
MusicGroup :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 26 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 43 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
SportsOrganization :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 44 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
SportsTeam :[
 { property_id: 11 , is_required: false }, 
 { property_id: 13 , is_required: false }, 
 { property_id: 33 , is_required: false }, 
 { property_id: 34 , is_required: false }, 
 { property_id: 35 , is_required: false }, 
 { property_id: 36 , is_required: false }, 
 { property_id: 37 , is_required: false }, 
 { property_id: 38 , is_required: false }, 
 { property_id: 39 , is_required: false }, 
 { property_id: 40 , is_required: false }, 
 { property_id: 41 , is_required: false }, 
 { property_id: 42 , is_required: false }, 
 { property_id: 44 , is_required: false }, 
 { property_id: 45 , is_required: false }, 
 { property_id: 46 , is_required: false }, 
 { property_id: 49 , is_required: false }, 
],
Place :[
 { property_id: 37 , is_required: false }, 
],
Accommodation :[
 { property_id: 37 , is_required: false }, 
],
AdministrativeArea :[
 { property_id: 37 , is_required: false }, 
],
City :[
 { property_id: 37 , is_required: false }, 
],
Country :[
 { property_id: 37 , is_required: false }, 
],
State :[
 { property_id: 37 , is_required: false }, 
],
CivicStructure :[
 { property_id: 37 , is_required: false }, 
],
Landform :[
 { property_id: 37 , is_required: false }, 
],
LandmarksOrHistoricalBuildings :[
 { property_id: 37 , is_required: false }, 
],
Residence :[
 { property_id: 37 , is_required: false }, 
],
TouristAttrcaction :[
 { property_id: 37 , is_required: false }, 
],
Product :[
 { property_id: 34 , is_required: false }, 
 { property_id: 47 , is_required: false },
]
}
